export default function Head() {
  return (
    <>
      <title>Manny Ortiz Profile</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="logo"
        href="/ai-mi-algorithm-svgrepo-com.png"
      />
    </>
  )
}
